return function(colors)
	return {
		Normal = { fg = colors.fg, bg = colors.bg },
		NormalNC = { fg = colors.fg_dim, bg = colors.bg },
		NormalFloat = { fg = colors.fg, bg = colors.bg_dark },
		Comment = { fg = colors.gray },
		LineNr = { fg = colors.blue_dark },
		Cursor = { fg = colors.bg, bg = colors.orange },
		CursorLineNr = { fg = colors.blue_light, bold = true },
		Keyword = { fg = colors.yellow },
		String = { fg = colors.yellow },
		Character = { fg = colors.yellow },
		EndOfBuffer = { fg = colors.bg, bg = colors.bg },
		Function = { fg = colors.blue },
		Macro = { fg = colors.magenta },
		Type = { fg = colors.blue_light },
		StorageClass = { fg = colors.blue_light },
		Structure = { fg = colors.blue_light },
		Typedef = { fg = colors.blue_light },
		Constant = { fg = colors.peach },
		Title = { fg = colors.orange, bold = true },
		NonText = { fg = colors.gray_dark },
		Special = { fg = colors.magenta },
		SpecialChar = { fg = colors.magenta },
		SpecialComment = { fg = colors.gray },
		Delimiter = { fg = colors.magenta },
		Tag = { fg = colors.blue_light },
		Debug = { fg = colors.magenta },
		MatchParen = { fg = colors.cream, bold = true },
		Statement = { fg = colors.yellow },
		Conditional = { fg = colors.yellow },
		Repeat = { fg = colors.yellow },
		Operator = { fg = colors.magenta },
		Exception = { fg = colors.yellow },
		PreProc = { fg = colors.magenta },
		Include = { fg = colors.magenta },
		Define = { fg = colors.magenta },
		PreCondit = { fg = colors.magenta },
		Number = { fg = colors.peach },
		Float = { fg = colors.peach },
		Boolean = { fg = colors.peach },
		Label = { fg = colors.yellow },
		Directory = { fg = colors.yellow, bold = true },
		Underlined = { fg = colors.blue_light, underline = true },
		Bold = { bold = true },
		Italic = { italic = true },
		Ignore = { fg = colors.bg },
		Error = { fg = colors.red, bold = true },
		Todo = { fg = colors.bg, bg = colors.cream, bold = true },

		-- UI Elements
		Visual = { bg = colors.gray_darker },
		CursorLine = { bg = colors.bg_light },
		CursorColumn = { bg = colors.bg_light },
		TermCursor = { fg = colors.bg, bg = colors.orange },
		lCursor = { fg = colors.bg, bg = colors.orange },
		CursorLineSign = { bg = colors.bg_light },
		CursorLineFold = { fg = colors.gray, bg = colors.bg_light },
		Search = { fg = colors.bg, bg = colors.yellow },
		CurSearch = { fg = colors.bg, bg = colors.orange, bold = true },
		IncSearch = { fg = colors.bg, bg = colors.orange },
		Substitute = { fg = colors.bg, bg = colors.magenta },
		FloatBorder = { fg = colors.blue_light, bg = colors.bg_dark },
		FloatTitle = { fg = colors.orange, bg = colors.bg_dark, bold = true },
		FloatFooter = { fg = colors.gray, bg = colors.bg_dark },
		WinSeparator = { fg = colors.blue_dark },
		WinBar = { fg = colors.fg_dim, bg = colors.bg_dark, bold = true },
		WinBarNC = { fg = colors.gray, bg = colors.bg_dark },
		Folded = { fg = colors.blue, bg = colors.bg_dark },
		FoldColumn = { fg = colors.gray, bg = colors.bg },
		SignColumn = { bg = colors.bg },
		ColorColumn = { bg = colors.bg_light },
		Conceal = { fg = colors.gray_dark },
		Whitespace = { fg = colors.gray_dark },
		SpecialKey = { fg = colors.gray_dark },
		MsgArea = { fg = colors.fg, bg = colors.bg },
		MoreMsg = { fg = colors.green },
		Question = { fg = colors.blue_light },
		QuickFixLine = { bg = colors.bg_light, bold = true },
		ErrorMsg = { fg = colors.red, bold = true },
		WarningMsg = { fg = colors.yellow, bold = true },
		ModeMsg = { fg = colors.orange, bold = true },

		-- Statusline / Tabline
		StatusLine = { fg = colors.fg_dim, bg = colors.bg_dark },
		StatusLineNC = { fg = colors.gray, bg = colors.bg_dark },
		TabLine = { fg = colors.gray, bg = colors.bg_dark },
		TabLineSel = { fg = colors.fg, bg = colors.bg_light, bold = true },
		TabLineFill = { bg = colors.bg_dark },

		-- Diff
		DiffAdd = { bg = colors.diff_add },
		DiffChange = { bg = colors.diff_change },
		DiffDelete = { fg = colors.red, bg = colors.diff_delete },
		DiffText = { bg = colors.diff_text, bold = true },
		Added = { fg = colors.green },
		Changed = { fg = colors.cream },
		Removed = { fg = colors.red },

		-- Diagnostics
		DiagnosticOk = { fg = colors.green },
		DiagnosticError = { fg = colors.red },
		DiagnosticWarn = { fg = colors.yellow },
		DiagnosticInfo = { fg = colors.cream },
		DiagnosticHint = { fg = colors.peach },
		DiagnosticDeprecated = { sp = colors.red, strikethrough = true },
		DiagnosticUnnecessary = { fg = colors.gray_dark },
		DiagnosticUnderlineError = { undercurl = true, sp = colors.red },
		DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
		DiagnosticUnderlineInfo = { undercurl = true, sp = colors.cream },
		DiagnosticUnderlineHint = { undercurl = true, sp = colors.peach },

		-- LSP
		LspReferenceText = { bold = true, sp = colors.blue },
		LspReferenceRead = { bold = true, sp = colors.green },
		LspReferenceWrite = { bold = true, sp = colors.orange },
		LspInlayHint = { fg = colors.gray, italic = true },
		LspCodeLens = { fg = colors.gray, italic = true },
		LspCodeLensSeparator = { fg = colors.gray_dark },
		LspSignatureActiveParameter = { fg = colors.orange, bold = true },

		-- Spelling
		SpellBad = { undercurl = true, sp = colors.red },
		SpellRare = { undercurl = true, sp = colors.magenta },
		SpellCap = { undercurl = true, sp = colors.blue_light },
		SpellLocal = { undercurl = true, sp = colors.green },
	}
end
