return function(colors)
	return {
		-- Completion Menu (Cmp + Blink)
		CmpItemAbbr = { fg = colors.fg },
		CmpItemAbbrDeprecated = { fg = colors.gray, strikethrough = true },
		CmpItemAbbrMatch = { fg = colors.blue_light, bold = true },
		CmpItemAbbrMatchFuzzy = { fg = colors.blue_light, bold = true },

		CmpItemKind = { fg = colors.blue },
		CmpItemMenu = { fg = colors.fg_dim },

		CmpItemKindMethod = { fg = colors.blue },
		CmpItemKindFunction = { fg = colors.blue },
		CmpItemKindConstructor = { fg = colors.blue },
		CmpItemKindClass = { fg = colors.blue_light },
		CmpItemKindInterface = { fg = colors.blue_light },
		CmpItemKindStruct = { fg = colors.blue_light },
		CmpItemKindModule = { fg = colors.blue_dark },
		CmpItemKindVariable = { fg = colors.orange },
		CmpItemKindProperty = { fg = colors.orange },
		CmpItemKindField = { fg = colors.orange },
		CmpItemKindConstant = { fg = colors.peach },
		CmpItemKindEnum = { fg = colors.yellow },
		CmpItemKindEnumMember = { fg = colors.yellow },
		CmpItemKindSnippet = { fg = colors.magenta },
		CmpItemKindKeyword = { fg = colors.yellow },
		CmpItemKindText = { fg = colors.fg_dim },
		CmpGhostText = { fg = colors.gray, italic = true },

		BlinkCmpLabel = { fg = colors.fg },
		BlinkCmpLabelMatch = { fg = colors.blue_light, bold = true },
		BlinkCmpLabelDeprecated = { fg = colors.gray, strikethrough = true },
		BlinkCmpLabelDetail = { fg = colors.fg_dim },
		BlinkCmpLabelDescription = { fg = colors.fg_dim },
		BlinkCmpSource = { fg = colors.fg_dim },
		BlinkCmpGhostText = { fg = colors.gray, italic = true },

		BlinkCmpMenu = { fg = colors.fg, bg = colors.bg_dark },
		BlinkCmpMenuBorder = { fg = colors.blue_light, bg = colors.bg_dark },
		BlinkCmpMenuSelection = { fg = colors.fg, bg = colors.bg_light, bold = true },
		BlinkCmpScrollBarGutter = { bg = colors.bg_dark },
		BlinkCmpScrollBarThumb = { bg = colors.gray_dark },

		BlinkCmpDoc = { fg = colors.fg, bg = colors.bg_dark },
		BlinkCmpDocBorder = { fg = colors.blue_light, bg = colors.bg_dark },
		BlinkCmpDocSeparator = { fg = colors.gray_dark, bg = colors.bg_dark },
		BlinkCmpDocCursorLine = { bg = colors.bg_light },

		BlinkCmpSignatureHelp = { fg = colors.fg, bg = colors.bg_dark },
		BlinkCmpSignatureHelpBorder = { fg = colors.blue_light, bg = colors.bg_dark },
		BlinkCmpSignatureHelpActiveParameter = { fg = colors.orange, bold = true },

		BlinkCmpKind = { fg = colors.blue },
		BlinkCmpKindMethod = { fg = colors.blue },
		BlinkCmpKindFunction = { fg = colors.blue },
		BlinkCmpKindConstructor = { fg = colors.blue },
		BlinkCmpKindClass = { fg = colors.blue_light },
		BlinkCmpKindInterface = { fg = colors.blue_light },
		BlinkCmpKindStruct = { fg = colors.blue_light },
		BlinkCmpKindModule = { fg = colors.blue_dark },
		BlinkCmpKindVariable = { fg = colors.orange },
		BlinkCmpKindProperty = { fg = colors.orange },
		BlinkCmpKindField = { fg = colors.orange },
		BlinkCmpKindConstant = { fg = colors.peach },
		BlinkCmpKindEnum = { fg = colors.yellow },
		BlinkCmpKindEnumMember = { fg = colors.yellow },
		BlinkCmpKindSnippet = { fg = colors.magenta },
		BlinkCmpKindKeyword = { fg = colors.yellow },
		BlinkCmpKindText = { fg = colors.fg_dim },
	}
end
