return function(colors)
	return {
		["@variable"] = { fg = colors.orange },
		["@variable.parameter.builtin"] = { fg = colors.orange, italic = true },
		["@keyword"] = { fg = colors.yellow },
		["@keyword.directive"] = { fg = colors.magenta },
		["@constructor"] = { fg = colors.blue },
		["@constructor.lua"] = { fg = colors.magenta },
		["@type"] = { fg = colors.blue_light },
		["@type.builtin"] = { fg = colors.blue_light, italic = true },
		["@type.definition"] = { fg = colors.blue_light },
		["@function"] = { fg = colors.blue },
		["@function.builtin"] = { fg = colors.blue, italic = true },
		["@function.call"] = { fg = colors.blue },
		["@function.macro"] = { fg = colors.magenta },
		["@function.method"] = { fg = colors.blue },
		["@function.method.call"] = { fg = colors.blue },
		["@variable.builtin"] = { fg = colors.orange, italic = true },
		["@string"] = { fg = colors.yellow },
		["@string.documentation"] = { fg = colors.cream },
		["@string.regexp"] = { fg = colors.magenta },
		["@string.escape"] = { fg = colors.magenta },
		["@string.special"] = { fg = colors.peach },
		["@string.special.url"] = { fg = colors.blue_light, underline = true },
		["@character"] = { fg = colors.yellow },
		["@character.special"] = { fg = colors.magenta },
		["@boolean"] = { fg = colors.peach },
		["@number"] = { fg = colors.peach },
		["@number.float"] = { fg = colors.peach },
		["@punctuation"] = { fg = colors.magenta },
		["@attribute"] = { fg = colors.magenta },
		["@attribute.builtin"] = { fg = colors.magenta, italic = true },
		["@constant"] = { fg = colors.peach },
		["@constant.builtin"] = { fg = colors.peach, italic = true },
		["@constant.macro"] = { fg = colors.magenta },
		["@operator"] = { fg = colors.magenta },
		["@comment"] = { fg = colors.gray },
		["@comment.error"] = { fg = colors.red, bold = true },
		["@comment.warning"] = { fg = colors.yellow, bold = true },
		["@comment.todo"] = { fg = colors.bg, bg = colors.cream, bold = true },
		["@comment.note"] = { fg = colors.blue_light, bold = true },
		["@markup.strong"] = { bold = true },
		["@markup.italic"] = { italic = true },
		["@markup.strikethrough"] = { strikethrough = true },
		["@markup.underline"] = { underline = true },
		["@markup.heading"] = { fg = colors.orange, bold = true },
		["@markup.quote"] = { fg = colors.gray },
		["@markup.math"] = { fg = colors.peach },
		["@markup.link"] = { fg = colors.blue_light },
		["@markup.link.label"] = { fg = colors.blue_light },
		["@markup.link.url"] = { fg = colors.blue_light, underline = true },
		["@markup.raw"] = { fg = colors.cream },
		["@markup.list"] = { fg = colors.magenta },
		["@markup.list.checked"] = { fg = colors.green },
		["@markup.list.unchecked"] = { fg = colors.gray },
		["@diff.plus"] = { fg = colors.green },
		["@diff.minus"] = { fg = colors.red },
		["@diff.delta"] = { fg = colors.cream },
		["@tag"] = { fg = colors.blue_light },
		["@tag.builtin"] = { fg = colors.blue_light, italic = true },
		["@tag.attribute"] = { fg = colors.peach },
		["@tag.delimiter"] = { fg = colors.magenta },
		["@module"] = { fg = colors.blue_dark },

		-- LSP semantic tokens
		["@lsp.type.class"] = { fg = colors.blue_light },
		["@lsp.type.decorator"] = { fg = colors.magenta },
		["@lsp.type.enum"] = { fg = colors.blue_light },
		["@lsp.type.enumMember"] = { fg = colors.peach },
		["@lsp.type.function"] = { fg = colors.blue },
		["@lsp.type.interface"] = { fg = colors.blue_light },
		["@lsp.type.keyword"] = { fg = colors.yellow },
		["@lsp.type.macro"] = { fg = colors.magenta },
		["@lsp.type.method"] = { fg = colors.blue },
		["@lsp.type.namespace"] = { fg = colors.blue_dark },
		["@lsp.type.number"] = { fg = colors.peach },
		["@lsp.type.operator"] = { fg = colors.magenta },
		["@lsp.type.parameter"] = { fg = colors.orange },
		["@lsp.type.regexp"] = { fg = colors.magenta },
		["@lsp.type.string"] = { fg = colors.yellow },
		["@lsp.type.struct"] = { fg = colors.blue_light },
		["@lsp.type.type"] = { fg = colors.blue_light },
		["@lsp.type.typeParameter"] = { fg = colors.blue_light },
		["@lsp.type.variable"] = { fg = colors.orange },
		["@lsp.mod.deprecated"] = { strikethrough = true },
		["@module.builtin"] = { fg = colors.blue_dark, italic = true },

		-- Neovim 0.9 / older nvim-treesitter highlights
		["@namespace"] = { fg = colors.blue_dark },
	}
end
